name: Update data

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9.2

      - name: Install requirements
        run: pip install -r ./requirements.txt

      - name: Execute data constructor Python script
        run: |
          python scripts/data_construcor.py
        
      - name: Set up git config
        run: |
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL }}

      - name: Commit changes
        run: |
          chmod +x scripts/commit.sh
          scripts/commit.sh