name: Update data

on:
  push:
    branches:
      - master

  #schedule:
    # runs on the first minute of every hour (TEST: EVERY 5TH MIN)
    #-cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with: 
          python-version: 3.7

      #- name: Install requirements
      #  run: pip install -r requirements.txt

      - name: Execute CSV reader script
        run: python3 csvReader.py