name: Update data

on:
  push:
    branches:
      - master

  schedule:
    -cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9.2

      - name: Execute CSV reader script
        run: |
        python csvReader.py